export const projects = [
  {
    id: 1,
    type: "Residential Plot",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Senior Citizen Villas",
    image: "/images/img68.jpg",
    thumbnail: "/images/img68.jpg",
    description:
      "Anubhava Mega City offers spacious villas for retired people in beautifully landscaped gardens. The 15-acre layout with 166 villas is spread in an integrated 400-acre Anubhava Mega City, with well developed infrastructure. The villas display hi-end designs and special features for the elderly. These unique villas celebrate your life and times among like-minded community.",
    discount: "10%",
  },
  {
    id: 2,
    type: "Commercial",
    place: "Office Building",
    area: "1500 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Convention Center",
    image: "/images/img100.jpg",
    thumbnail: "/images/img100.jpg",
    description:
      "The main hall at Anubhava Convention Center adapts beautifully from morning conferences to evening celebrations. Natural light fills our spaces through tall windows, while modern acoustics ensure clear sound reaches every corner. Thoughtfully designed breakout rooms give smaller groups perfect spaces to connect and create. The open layout lets your guests move easily between spaces, making every event flow naturally.",
    discount: "10%",
  },
  {
    id: 3,
    type: "Residential",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Anubhava Mega Layout",
    image: "/images/img91.jpg",
    thumbnail: "/images/img91.jpg",
    description: "",
    discount: "10%",
  },
  {
    id: 4,
    type: "Residential",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Senior Citizen Villas",
    image: "/images/img100.jpg",
    thumbnail: "/images/img100.jpg",
    description: "",
    discount: "20%",
  },
  {
    id: 5,
    type: "Commercial Plot",
    place: "Office Building",
    area: "1500 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Convention Center",
    image: "/images/img91.jpg",
    thumbnail: "/images/img91.jpg",
    description: "",
    discount: "15%",
  },
  {
    id: 6,
    type: "Residential",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Anubhava Mega Layout",
    image: "/images/img100.jpg",
    thumbnail: "/images/img100.jpg",
    description: "",
    discount: "10%",
  },
  {
    id: 7,
    type: "Farm Land",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Senior Citizen Villas",
    image: "/images/img68.jpg",
    thumbnail: "/images/img68.jpg",
    description:
      "Anubhava Mega City offers spacious villas for retired people in beautifully landscaped gardens. The 15-acre layout with 166 villas is spread in an integrated 400-acre Anubhava Mega City, with well developed infrastructure. The villas display hi-end designs and special features for the elderly. These unique villas celebrate your life and times among like-minded community.",
  },
  {
    id: 8,
    type: "Commercial",
    place: "Office Building",
    area: "1500 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Convention Center",
    image: "/images/img100.jpg",
    thumbnail: "/images/img100.jpg",
    description:
      "The main hall at Anubhava Convention Center adapts beautifully from morning conferences to evening celebrations. Natural light fills our spaces through tall windows, while modern acoustics ensure clear sound reaches every corner. Thoughtfully designed breakout rooms give smaller groups perfect spaces to connect and create. The open layout lets your guests move easily between spaces, making every event flow naturally.",
  },
  {
    id: 9,
    type: "Residential",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Anubhava Mega Layout",
    image: "/images/img91.jpg",
    thumbnail: "/images/img91.jpg",
    description: "",
  },
  {
    id: 10,
    type: "Residential",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Senior Citizen Villas",
    image: "/images/img100.jpg",
    thumbnail: "/images/img100.jpg",
    description: "",
  },
  {
    id: 11,
    type: "Commercial",
    place: "Office Building",
    area: "1500 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Convention Center",
    image: "/images/img91.jpg",
    thumbnail: "/images/img91.jpg",
    description: "",
  },
  {
    id: 12,
    type: "Residential",
    place: "Apartment Complex",
    area: "1200 sq ft",
    location: "Anubhav Mega City, Basava Kalyan",
    name: "Anubhava Mega Layout",
    image: "/images/img100.jpg",
    thumbnail: "/images/img100.jpg",
    description: "",
  },
];
